### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by hutchic** [api-meetups/website#1]

**Comment by ahmadnassri** [comment]
hmmm bizarre, since it's cloudflare

**Comment by ahmadnassri** [comment]
nope. still works

**Comment by hutchic** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=api.meetups.tech&hideResults=on

certificate name mismatch

**Comment by ahmadnassri** [comment]
ooooh, well this was never linked as an `https` link, always use `http`

**Comment by ahmadnassri** [comment]
where did you see `https` being used?

**Comment by hutchic** [comment]
here https://github.com/api-meetups

**Comment by hutchic** [comment]
ping :)

**Comment by hutchic** [comment]
:+1:
